(define prompt "Enter a value for ")
(display (string-append prompt "A: "))
(define a (string->number (read-line)))
(display (string-append prompt "B: "))
(define b (string->number (read-line)))
(display (string-append prompt "C: "))
(define c (string->number (read-line)))

(define d (sqrt (- (* b b) (* 4.0 a c))))

(newline)
(display (/ (- (- b) d) (* 2.0 a)))
(newline)
(display (/ (+ (- b) d) (* 2.0 a)))
(newline)
